name: career_guide
description: "AI-assisted Career Guidance & Job Recommender App"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Utility Packages
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.2
  http: ^1.1.0
  csv: ^5.0.2
  cached_network_image: ^3.3.0
  image_picker: ^1.0.7

  # Firebase Packages
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_auth_web: ^5.12.0
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.5
  firebase_storage_web: ^3.6.22
  js: ^0.6.7
  js_wrapping: ^0.7.4

  # Social Sign-in Packages
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.4
  sign_in_with_apple: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/data/jobs.json