// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Kuc4TJ2YFgN7Aty7ILUMSZ9PsMF94SU',
    appId: '1:1008511971667:web:f535f57a4de68d30d571a6',
    messagingSenderId: '1008511971667',
    projectId: 'path-x',
    authDomain: 'path-x.firebaseapp.com',
    storageBucket: 'path-x.firebasestorage.app',
    measurementId: 'G-HJCGX796YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-sYvp4Om2cePJ0ZwcOUzGFWShMF4w3CU',
    appId: '1:1008511971667:android:b4b1ecf3934380f8d571a6',
    messagingSenderId: '1008511971667',
    projectId: 'path-x',
    storageBucket: 'path-x.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTMutsfdQ6EeIPtKuNNq5y3J95VmQXqbQ',
    appId: '1:1008511971667:ios:21eda920d904d29dd571a6',
    messagingSenderId: '1008511971667',
    projectId: 'path-x',
    storageBucket: 'path-x.firebasestorage.app',
    iosBundleId: 'com.example.pathx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTMutsfdQ6EeIPtKuNNq5y3J95VmQXqbQ',
    appId: '1:1008511971667:ios:21eda920d904d29dd571a6',
    messagingSenderId: '1008511971667',
    projectId: 'path-x',
    storageBucket: 'path-x.firebasestorage.app',
    iosBundleId: 'com.example.pathx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7Kuc4TJ2YFgN7Aty7ILUMSZ9PsMF94SU',
    appId: '1:1008511971667:web:ee0af5917e72b20bd571a6',
    messagingSenderId: '1008511971667',
    projectId: 'path-x',
    authDomain: 'path-x.firebaseapp.com',
    storageBucket: 'path-x.firebasestorage.app',
    measurementId: 'G-42ZTGGYB8S',
  );
}
