name: db_migrations
description: Database migration scripts for PathX
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mongo_dart: ^0.10.0
  dotenv: ^4.2.0
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
